title:             Cre8iveroom
email:             cre8iveroom@gmail.com
description:       Experiments by Cre8iveroom
author:            Cre8iveroom
baseurl:           ""
url:               "https://cre8iveroom.com"

# Social Profiles
twitter_username:  Cre8iveroom
github_username:   Cre8iveroom
facebook_username: Cre8iveroom

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate